<?php if ( ! defined( 'ABSPATH' ) ) {
	die; } // Cannot access directly.

//
// Create a section
//
WPGPSC::createSection(
	$wpgpsc_page_opts,
	array(
		'title'  => __( 'Appearance', 'gpsc-product-slider-carousel' ),
		'icon'   => 'fas fa-layer-group',
		'fields' => array(

			array(
				'type'    => 'content',
				'content' => '<style>[class*="notice"],.faqsu-field-content-style{display: none !important;}</style>
				<div class="wpgpsc--menu-detail">
					<strong>Appearance</strong>
					<a href="https://pluginic.com/support/" target="_blank" class="">Need Help?</a>
					<br>
					<p>The Appearance options allow you to manage the display settings according to different modules. Use the product query to choose the items you want to display. The Visibility options give you further control, enabling you to show or hide specific parts of an item.</p>
				</div>',
			),

			array(
				'type'       => 'subheading',
				'content'    => '<i class="fas fa-grip-lines"></i> Select a Module First <i class="fas fa-grip-lines"></i>',
				'class'      => 'wpgpsc-subheading',
				'dependency' => array( 'wpgpsc_module', '!=', 'cd-timer' ),
			),
			array(
				'id'      => 'wpgpsc_module',
				'type'    => 'image_select',
				'options' => array(
					'grid-carousel' => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/1.png',
					'slider'        => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/2.png',
					'table'         => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/3.png',
					'highlighted'   => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/4.png',
					'with-banner'   => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/5.png',
					'grouped'       => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/6.png',
					'category'      => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/7.png',
					'reviews'       => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/8.png',
					'cd-timer'      => GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules/9.png',
				),
				'default' => 'grid-carousel',
				'class'   => 'wpgpsc-module-img-select',
			),
			array(
				'id'          => 'wpgpsc_highlight_product_selected',
				'type'        => 'select',
				'title'       => __( 'Select Highlighted Product', 'gpsc-product-slider-carousel' ),
				'subtitle'    => __( 'Select a product for highlighted or showing first one.', 'gpsc-product-slider-carousel' ),
				'placeholder' => 'Select a product',
				'chosen'      => true,
				'ajax'        => true,
				'multiple'    => false,
				'options'     => 'posts',
				'query_args'  => array(
					'post_type' => 'product',
				),
				'dependency'  => array( 'wpgpsc_module', '==', 'highlighted' ),
			),

			//
			// Category template.
			//
			array(
				'id'         => 'wpgpsc_cat_template_set',
				'type'       => 'button_set',
				'title'      => 'Category Template',
				'options'    => array(
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5',
					'6' => '6',
				),
				'default'    => '1',
				'dependency' => array( 'wpgpsc_module', '==', 'category' ),
			),
			array(
				'type'       => 'content',
				'content'    => '<img width="600" src="' . GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules-cat/cat-1.jpg">',
				'class'      => 'wpgpsc-cat-cont-img',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|1' ),
			),
			array(
				'type'       => 'content',
				'content'    => '<img width="600" src="' . GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules-cat/cat-2.jpg">',
				'class'      => 'wpgpsc-cat-cont-img',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|2' ),
			),
			array(
				'type'       => 'content',
				'content'    => '<img width="600" src="' . GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules-cat/cat-3.jpg">',
				'class'      => 'wpgpsc-cat-cont-img',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|3' ),
			),
			array(
				'type'       => 'content',
				'content'    => '<img width="600" src="' . GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules-cat/cat-4.jpg">',
				'class'      => 'wpgpsc-cat-cont-img',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|4' ),
			),
			array(
				'type'       => 'content',
				'content'    => '<img width="600" src="' . GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules-cat/cat-5.jpg">',
				'class'      => 'wpgpsc-cat-cont-img',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|5' ),
			),
			array(
				'type'       => 'content',
				'content'    => '<img width="600" src="' . GPSC_PLUG_DIR_URL_FILE . 'admin/img/modules-cat/cat-6.png">',
				'class'      => 'wpgpsc-cat-cont-img',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|6' ),
			),

			/**
			 * Only for category 5.
			 */
			array(
				'id'         => 'wpgpsc_cat_menu_name',
				'type'       => 'text',
				'title'      => 'Menu Name',
				'subtitle'   => 'Set a menu name.',
				'default'    => 'All Categories',
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|5' ),
			),
			array(
				'id'             => 'wpgpsc_cat_default_icon',
				'type'           => 'media',
				'title'          => 'Default Menu Icon',
				'subtitle'       => 'Set a default menu icon.<br>Maximum size is 24x24px.',
				'url'            => false,
				'preview_width'  => 24,
				'preview_height' => 24,
				'default'        => array(
					'url'       => GPSC_PLUG_DIR_URL_FILE . 'public/img/shopping-bag.png',
					'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'public/img/shopping-bag.png',
				),
				'class'          => 'wpgpsc-media-preview',
				'dependency'     => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|5' ),
			),
			array(
				'id'         => 'wpgpsc_cat_menu_item_before_accordion',
				'type'       => 'accordion',
				'accordions' => array(
					array(
						'title'  => 'Add Menu Before',
						'icon'   => 'fa fa-plus',
						'fields' => array(
							array(
								'id'           => 'wpgpsc_cat_menu_item_before',
								'type'         => 'repeater',
								'fields'       => array(
									array(
										'id'       => 'wpgpsc_cat_menu_item_before_link',
										'type'     => 'link',
										'title'    => 'Menu Link Before',
										'subtitle' => 'Set a link for the menu item that comes before the others.',
									),
									array(
										'id'             => 'wpgpsc_cat_menu_item_before_icon',
										'type'           => 'media',
										'title'          => 'Menu Icon Before',
										'subtitle'       => 'Set a default menu icon.<br>Maximum size is 24x24px.',
										'url'            => false,
										'preview_width'  => 24,
										'preview_height' => 24,
										'class'          => 'wpgpsc-media-preview',
									),
								),
								'button_title' => '+ Add New Icon',
							),
						),
					),
				),
				'default'    => array(
					'wpgpsc_cat_menu_item_before' => array(
						array(
							'wpgpsc_cat_menu_item_before_link' => array(
								'url'    => '#',
								'text'   => 'Featured',
								'target' => '_blank',
							),
							'wpgpsc_cat_menu_item_before_icon' => array(
								'url'       => GPSC_PLUG_DIR_URL_FILE . 'public/img/features.png',
								'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'public/img/features.png',
							),
						),
						array(
							'wpgpsc_cat_menu_item_before_link' => array(
								'url'    => '#',
								'text'   => 'Top Sell',
								'target' => '_blank',
							),
							'wpgpsc_cat_menu_item_before_icon' => array(
								'url'       => GPSC_PLUG_DIR_URL_FILE . 'public/img/hot.png',
								'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'public/img/hot.png',
							),
						),
					),
				),
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|5' ),
			),
			array(
				'id'         => 'wpgpsc_cat_menu_item_after_accordion',
				'type'       => 'accordion',
				'accordions' => array(
					array(
						'title'  => 'Add Menu After',
						'icon'   => 'fa fa-plus',
						'fields' => array(
							array(
								'id'           => 'wpgpsc_cat_menu_item_after',
								'type'         => 'repeater',
								'fields'       => array(
									array(
										'id'       => 'wpgpsc_cat_menu_item_after_link',
										'type'     => 'link',
										'title'    => 'Menu Link After',
										'subtitle' => 'Set a link for the menu item that comes after the others.',
									),
									array(
										'id'             => 'wpgpsc_cat_menu_item_after_icon',
										'type'           => 'media',
										'title'          => 'Menu Icon After',
										'subtitle'       => 'Set a default menu icon.<br>Maximum size is 24x24px.',
										'url'            => false,
										'preview_width'  => 24,
										'preview_height' => 24,
										'class'          => 'wpgpsc-media-preview',
									),
								),
								'button_title' => '+ Add New Icon',
							),
						),
					),
				),
				'default'    => array(
					'wpgpsc_cat_menu_item_after' => array(
						array(
							'wpgpsc_cat_menu_item_after_link' => array(
								'url'    => '#',
								'text'   => 'Coupons',
								'target' => '_blank',
							),
							'wpgpsc_cat_menu_item_after_icon' => array(
								'url'       => GPSC_PLUG_DIR_URL_FILE . 'public/img/promo-code.png',
								'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'public/img/promo-code.png',
							),
						),
					),
				),
				'dependency' => array( 'wpgpsc_module|wpgpsc_cat_template_set', '==|==', 'category|5' ),
			),

			//
			// Random options.
			//
			array(
				'id'         => 'wpgpsc_carousel_mode_on',
				'type'       => 'switcher',
				'title'      => __( 'Carousel Mode', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Gid view in carousel mode or not.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'On', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Off', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'any', 'grid-carousel,highlighted,with-banner,grouped,category,reviews' ),
			),
			array(
				'id'         => 'wpgpsc_content_flow',
				'type'       => 'button_set',
				'title'      => 'Content Flow',
				'subtitle'   => 'Grid view content flow direction.',
				'options'    => array(
					'horizontal' => 'Horizontal',
					'vertical'   => 'Vertical',
				),
				'default'    => 'vertical',
				'dependency' => array( 'wpgpsc_module', '==', 'grid-carousel' ),
			),
			array(
				'id'         => 'wpgpsc_cat_parent_only',
				'type'       => 'switcher',
				'title'      => __( 'Only Parent Categories?', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show only parent cateogoires.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Yes', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'No', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', 'any', 'grouped,category' ),
			),
			array(
				'id'         => 'wpgpsc_section_title_show',
				'type'       => 'switcher',
				'title'      => __( 'Show the section title', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide the section title.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 80,
				'default'    => true,
			),
			array(
				'id'                => 'wpgpsc_section_title_margin_bottom',
				'type'              => 'dimensions',
				'title'             => __( 'Section Title Margin Bottom', 'gpsc-product-slider-carousel' ),
				'subtitle'          => __( 'Set margin bottom form section title.', 'gpsc-product-slider-carousel' ),
				'height'            => false,
				'width_icon'        => '',
				'width_placeholder' => '',
				'units'             => array( 'px' ),
				'default'           => array(
					'width' => '10',
				),
				'dependency'        => array( 'wpgpsc_section_title_show', '==', 'true' ),
			),
			array(
				'id'         => 'wpgpsc_product_rows',
				'type'       => 'spinner',
				'title'      => __( 'Product Rows', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Number of row\'s of products.', 'gpsc-product-slider-carousel' ),
				'dependency' => array( 'wpgpsc_module', 'any', 'grid-carousel,highlighted,with-banner' ),
			),
			array(
				'id'         => 'wpgpsc_product_columns',
				'type'       => 'spinner',
				'title'      => __( 'Item Columns', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Number of column\'s of items/products.', 'gpsc-product-slider-carousel' ),
				'default'    => 3,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'slider,list,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_product_space_between',
				'type'       => 'spinner',
				'title'      => __( 'Items Space Between', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Distance between items in px.', 'gpsc-product-slider-carousel' ),
				'default'    => 20,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'slider,list,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_slider_full_width',
				'type'       => 'switcher',
				'title'      => __( 'Slider Full Width', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set the full width slider for a hero area.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'On', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Off', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'slider' ),
			),
			array(
				'id'                => 'wpgpsc_section_width',
				'type'              => 'dimensions',
				'title'             => __( 'Section Width', 'gpsc-product-slider-carousel' ),
				'subtitle'          => __( 'Maximum width of the section.', 'gpsc-product-slider-carousel' ),
				'height'            => false,
				'width_icon'        => '',
				'width_placeholder' => '',
				'units'             => array( 'px' ),
				'default'           => array(
					'width' => '1100',
				),
			),
			array(
				'id'                => 'wpgpsc_inner_width',
				'type'              => 'dimensions',
				'title'             => __( 'Inner Width', 'gpsc-product-slider-carousel' ),
				'subtitle'          => __( 'Maximum width of the inner content of the slider.', 'gpsc-product-slider-carousel' ),
				'height'            => false,
				'width_icon'        => '',
				'width_placeholder' => '',
				'units'             => array( 'px' ),
				'default'           => array(
					'width' => '900',
				),
				'dependency'        => array( 'wpgpsc_module', '==', 'slider' ),
			),
			array(
				'id'                => 'wpgpsc_min_height',
				'type'              => 'dimensions',
				'title'             => __( 'Minimum Height', 'gpsc-product-slider-carousel' ),
				'subtitle'          => __( 'Minimum height of the slider.', 'gpsc-product-slider-carousel' ),
				'height'            => false,
				'width_icon'        => '',
				'width_placeholder' => '',
				'units'             => array( 'px' ),
				'default'           => array(
					'width' => '700',
				),
				'dependency'        => array( 'wpgpsc_module', 'any', 'slider,cd-timer' ),
			),
			array(
				'id'                => 'wpgpsc_max_height',
				'type'              => 'dimensions',
				'title'             => __( 'Maximum Height', 'gpsc-product-slider-carousel' ),
				'subtitle'          => __( 'Maximum height of category navigation' ),
				'height'            => false,
				'width_icon'        => '',
				'width_placeholder' => '',
				'units'             => array( 'px' ),
				'default'           => array(
					'width' => '350',
				),
				'dependency'        => array( 'wpgpsc_module|wpgpsc_cat_template_set', 'any|==', 'category|5' ),
			),
			array(
				'id'             => 'wpgpsc_slider_bg_img',
				'type'           => 'media',
				'title'          => 'Background Image',
				'subtitle'       => 'Set a background image.<br>If you don\'t want, just remove it.',
				'url'            => false,
				'preview_width'  => 300,
				'preview_height' => 300,
				'default'        => array(
					'url'       => GPSC_PLUG_DIR_URL_FILE . 'public/img/slider-bg-blue.jpg',
					'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'public/img/slider-bg-blue.jpg',
				),
				'class'          => 'wpgpsc-media-preview',
				'dependency'     => array( 'wpgpsc_module', 'any', 'slider,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_slider_bg_overlay',
				'type'       => 'slider',
				'title'      => 'Background Overlay',
				'subtitle'   => 'Set background overlay opacity.',
				'min'        => 0,
				'max'        => 100,
				'default'    => 70,
				'class'      => 'wpgp-field-w-350',
				'dependency' => array( 'wpgpsc_module', 'any', 'slider,cd-timer' ),
			),
			array(
				'id'                 => 'wpgpsc_slider_responsive',
				'type'               => 'spacing',
				'title'              => 'Slider Responsive',
				'subtitle'           => 'Set different responsive breakpoints for different screen sizes.',
				'top_icon'           => '<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="#530fa5" d="M64 0C28.7 0 0 28.7 0 64V352c0 35.3 28.7 64 64 64H240l-10.7 32H160c-17.7 0-32 14.3-32 32s14.3 32 32 32H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H346.7L336 416H512c35.3 0 64-28.7 64-64V64c0-35.3-28.7-64-64-64H64zM512 64V352H64V64H512z"/></svg>',
				'top_placeholder'    => 'Large',
				'right_icon'         => '<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="#530fa5" d="M0 64C0 28.7 28.7 0 64 0H384c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V64zM256 448a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zM384 64H64V384H384V64z"/></svg>',
				'right_placeholder'  => 'Medium',
				'bottom_icon'        => '<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="#530fa5" d="M16 64C16 28.7 44.7 0 80 0H304c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H80c-35.3 0-64-28.7-64-64V64zM144 448c0 8.8 7.2 16 16 16h64c8.8 0 16-7.2 16-16s-7.2-16-16-16H160c-8.8 0-16 7.2-16 16zM304 64H80V384H304V64z"/></svg>',
				'bottom_placeholder' => 'Small',
				'left'               => false,
				'show_units'         => false,
				'default'            => array(
					'top'    => '3', // Large.
					'right'  => '2', // Medium.
					'bottom' => '1', // Small.
				),
				'dependency'         => array( 'wpgpsc_module', 'not-any', 'table,cd-timer' ),
			),

			//
			// Banner Options.
			//
			array(
				'type'       => 'subheading',
				'content'    => '<i class="fas fa-grip-lines"></i> Banner Options <i class="fas fa-grip-lines"></i>',
				'class'      => 'wpgpsc-subheading',
				'dependency' => array( 'wpgpsc_module', '==', 'with-banner' ),
			),
			array(
				'id'         => 'wpgpsc_banner_bg_type',
				'type'       => 'button_set',
				'title'      => 'Banner Background',
				'subtitle'   => 'If you set color as banner background,<br>set background color from <strong><em>Colors</em></strong> tab option.',
				'options'    => array(
					'img' => 'Image',
					'col' => 'Color',
				),
				'default'    => 'img',
				'dependency' => array( 'wpgpsc_module', '==', 'with-banner' ),
			),
			array(
				'id'             => 'wpgpsc_banner_img',
				'type'           => 'media',
				'title'          => 'Background Image',
				'subtitle'       => 'Set a banner background image.',
				'library'        => 'image',
				'url'            => false,
				'default'        => array(
					'url'       => GPSC_PLUG_DIR_URL_FILE . 'public/img/banner-bg-default.jpg',
					'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'public/img/banner-bg-default.jpg',
				),
				'preview_width'  => 200,
				'preview_height' => 400,
				'dependency'     => array( 'wpgpsc_module|wpgpsc_banner_bg_type', '==|==', 'with-banner|img' ),
			),
			array(
				'id'         => 'wpgpsc_banner_content_show',
				'type'       => 'switcher',
				'title'      => __( 'Show Banner Content', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'You can use a single image as a banner or use custom content with banner image.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 80,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'with-banner' ),
			),
			array(
				'id'         => 'wpgpsc_banner_content_fieldset',
				'type'       => 'fieldset',
				'title'      => 'Banner Front Content',
				'subtitle'   => 'Use those content as a front of banner.<br>If you don\'t want to show any particular content, just leave it blank.',
				'fields'     => array(
					array(
						'id'      => 'wpgpsc_banner_content_img',
						'type'    => 'media',
						'title'   => 'Image :',
						'library' => 'image',
						'url'     => false,
						'default' => array(
							'url'       => GPSC_PLUG_DIR_URL_FILE . 'admin/img/banner-image-demo.png',
							'thumbnail' => GPSC_PLUG_DIR_URL_FILE . 'admin/img/banner-image-demo.png',
						),
					),
					array(
						'id'      => 'wpgpsc_banner_content_title',
						'type'    => 'text',
						'title'   => 'Title :',
						'default' => '50% OFF NOW!!',
					),
					array(
						'id'      => 'wpgpsc_banner_content_subtitle',
						'type'    => 'textarea',
						'title'   => 'Subtitle :',
						'default' => 'Get groceries delivered on your doorsteps with one click!',
					),
				),
				'dependency' => array( 'wpgpsc_module|wpgpsc_banner_content_show', '==|==', 'with-banner|true' ),
			),
			array(
				'id'         => 'wpgpsc_banner_link',
				'type'       => 'link',
				'title'      => 'Banner/Button Link',
				'subtitle'   => 'Set a banner or button link to clickable.',
				'default'    => array(
					'url'    => 'https://pluginic.com/plugins/product-slider-carousel/',
					'text'   => 'Download',
					'target' => '_blank',
				),
				'dependency' => array( 'wpgpsc_module', '==', 'with-banner' ),
			),
			array(
				'id'         => 'wpgpsc_banner_position',
				'type'       => 'button_set',
				'title'      => 'Banner Position',
				'subtitle'   => 'Set banner position.',
				'options'    => array(
					'left'  => 'Left',
					'right' => 'Right',
				),
				'default'    => 'left',
				'dependency' => array( 'wpgpsc_module', '==', 'with-banner' ),
			),

			//
			// Countdown Timer.
			//
			array(
				'id'          => 'wpgpsc-datetime',
				'type'        => 'datetime',
				'title'       => 'Set Start to End Date',
				'subtitle'    => 'Set date for Countdown Timer.',
				'placeholder' => 'Click to open a datetime',
				'from_to'     => true,
				'settings'    => array(
					'altFormat'  => 'F j, Y',
					'dateFormat' => 'Y-m-d',
				),
				'dependency'  => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-deadline-end-time',
				'type'       => 'datetime',
				'title'      => 'Deadline Time',
				'subtitle'   => 'Set a deadline time that make your deadline more specific and exact. If you don\'t want to set just leave it as blank. Default time 00:00:00',
				'settings'   => array(
					'noCalendar' => true,
					'enableTime' => true,
				),
				'default'    => '00:00:00',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_only_timer_show',
				'type'       => 'switcher',
				'title'      => __( 'Show Only Timer', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Turn on to show only timer so that you can insert into another content.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'On', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Off', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_content_alignment',
				'type'       => 'button_set',
				'title'      => 'Alignment',
				'subtitle'   => 'Set alignment of content.',
				'options'    => array(
					'left'   => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M288 64c0 17.7-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32H256c17.7 0 32 14.3 32 32zm0 256c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H256c17.7 0 32 14.3 32 32zM0 192c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 448c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>',
					'center' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M352 64c0-17.7-14.3-32-32-32H128c-17.7 0-32 14.3-32 32s14.3 32 32 32H320c17.7 0 32-14.3 32-32zm96 128c0-17.7-14.3-32-32-32H32c-17.7 0-32 14.3-32 32s14.3 32 32 32H416c17.7 0 32-14.3 32-32zM0 448c0 17.7 14.3 32 32 32H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H32c-17.7 0-32 14.3-32 32zM352 320c0-17.7-14.3-32-32-32H128c-17.7 0-32 14.3-32 32s14.3 32 32 32H320c17.7 0 32-14.3 32-32z"/></svg>',
					'right'  => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M448 64c0 17.7-14.3 32-32 32H192c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32zm0 256c0 17.7-14.3 32-32 32H192c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32zM0 192c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 448c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>',
				),
				'default'    => 'center',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),

			//
			// Content before start.
			//
			array(
				'type'       => 'subheading',
				'content'    => '<span>Content Before Start</span><br><i>Set content when the countdown has not started yet.</i>',
				'class'      => 'wpgpsc-cd-subheading',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-cd-content-before',
				'type'       => 'wp_editor',
				'height'     => '100px',
				'default'    => '<h3>Flash Sale Countdown Begins Soon! ⏲️</h3>
				<p>Exciting discounts are just around the corner! We\'re counting down to an epic flash sale that you don\'t want to miss. Stay tuned and get your wish-list ready. Discounts of up to 70% on your favorite items will be available for a limited time.</p>',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-cd-link-before',
				'type'       => 'link',
				'title'      => 'Button Link',
				'subtitle'   => 'Set a button link for the countdown when it has not started yet.',
				'default'    => array(
					'url'    => '#',
					'text'   => 'Contact for Updates 💬',
					'target' => '_blank',
				),
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),

			//
			// Content when running.
			//
			array(
				'type'       => 'subheading',
				'content'    => '<span>Content For Running Event</span><br><i>Set content when the countdown is currently running.</i>',
				'class'      => 'wpgpsc-cd-subheading',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-cd-content-running',
				'type'       => 'wp_editor',
				'default'    => '<h3>Now Live - Our Unmissable Flash Sale! ⚡️</h3>
				<p>The clock is ticking as our flash sale has officially launched! With up to 70% off, this limited-time event offers unbeatable bargains. Make a beeline for your most-wanted items and secure them before the countdown ends and the deals vanish. Time is of the essence...Seize the savings now!</p>',
				'height'     => '100px',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-cd-link-running',
				'type'       => 'link',
				'title'      => 'Button Link',
				'subtitle'   => 'Set a link for the countdown when it is currently running.',
				'default'    => array(
					'url'    => '#',
					'text'   => 'Shop Now 🛍️',
					'target' => '_blank',
				),
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),

			//
			// Content when end.
			//
			array(
				'type'       => 'subheading',
				'content'    => '<span>Content After Event End</span><br><i>Set content when the countdown has ended.</i>',
				'class'      => 'wpgpsc-cd-subheading',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-cd-content-end',
				'type'       => 'wp_editor',
				'default'    => '<h3>And... It\'s Over! 😮</h3>
				<p>Our flash sale has ended. We hope you managed to snag some great deals! If you missed out, don\'t worry. We\'ll be back with more amazing sales soon.</p>',
				'height'     => '100px',
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc-cd-link-end',
				'type'       => 'link',
				'title'      => 'Button Link',
				'subtitle'   => 'Set a link for the countdown when the countdown has ended.',
				'default'    => array(
					'url'    => '#',
					'text'   => 'Contact for Updates 💬',
					'target' => '_blank',
				),
				'dependency' => array( 'wpgpsc_module', '==', 'cd-timer' ),
			),

			//
			// Query Options.
			//
			array(
				'type'       => 'subheading',
				'content'    => '<i class="fas fa-grip-lines"></i> Product Query <i class="fas fa-grip-lines"></i>',
				'class'      => 'wpgpsc-subheading',
				'dependency' => array( 'wpgpsc_module', '!=', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_5_star_reviews',
				'type'       => 'switcher',
				'title'      => __( 'Only 5 Star Reviews?', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show only 5 star reviews or not.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Yes', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'No', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),
			array(
				'id'          => 'wpgpsc_product_by',
				'type'        => 'select',
				'title'       => 'Product By',
				'subtitle'    => 'Select a query type.',
				'placeholder' => 'Select a option',
				'options'     => array(
					'default'   => 'Default',
					'category'  => 'Category',
					'hand-pick' => 'Hand Pick',
					'featured'  => 'Featured',
					'top_sales' => 'Top Sales',
				),
				'default'     => 'default',
				'dependency'  => array( 'wpgpsc_module', '!=', 'cd-timer' ),
			),
			array(
				'id'          => 'wpgpsc_product_cat_selection',
				'type'        => 'select',
				'title'       => 'Select a category',
				'subtitle'    => 'Show only selected categories of products.',
				'placeholder' => 'Select a category',
				'chosen'      => true,
				'multiple'    => true,
				'options'     => 'wpgpsc_get_product_cat',
				'dependency'  => array( 'wpgpsc_product_by|wpgpsc_module', '==|not-any', 'category|reviews' ),
			),
			array(
				'id'          => 'wpgpsc_product_review_cat_selection',
				'type'        => 'select',
				'title'       => 'Select a category',
				'subtitle'    => 'Select a category of product reviews.',
				'placeholder' => 'Select a category',
				'options'     => 'wpgpsc_get_product_cat',
				'dependency'  => array( 'wpgpsc_product_by|wpgpsc_module', '==|==', 'category|reviews' ),
			),
			array(
				'id'          => 'wpgpsc_specific_product_selected',
				'type'        => 'select',
				'title'       => __( 'Select Specific Products', 'gpsc-product-slider-carousel' ),
				'subtitle'    => __( 'Select some specific products.', 'gpsc-product-slider-carousel' ),
				'placeholder' => 'Select a product',
				'chosen'      => true,
				'ajax'        => true,
				'multiple'    => true,
				'options'     => 'posts',
				'query_args'  => array(
					'post_type' => 'product',
				),
				'dependency'  => array( 'wpgpsc_product_by', '==', 'hand-pick' ),
			),
			array(
				'id'         => 'wpgpsc_cat_limit',
				'type'       => 'spinner',
				'title'      => __( 'Category Limit', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Maximum number of category to show. Leave blank for show all.', 'gpsc-product-slider-carousel' ),
				'dependency' => array( 'wpgpsc_module', '==', 'category' ),
			),
			array(
				'id'         => 'wpgpsc_product_limit',
				'type'       => 'spinner',
				'title'      => __( 'Product Limit', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Maximum number of results to show products or -1 for unlimited.', 'gpsc-product-slider-carousel' ),
				'default'    => -1,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer,category' ),
			),
			array(
				'id'         => 'wpgpsc_review_limit',
				'type'       => 'spinner',
				'title'      => __( 'Review Limit', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Maximum number of reviews to show. Leave blank to no limit.', 'gpsc-product-slider-carousel' ),
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),
			array(
				'id'         => 'wpgpsc_product_orderby',
				'type'       => 'select',
				'title'      => 'Orderby',
				'subtitle'   => 'Sorting your products by order options.',
				'options'    => array(
					'none'     => 'None',
					'ID'       => 'ID',
					'name'     => 'Name',
					'type'     => 'Type',
					'rand'     => 'Rand',
					'date'     => 'Date',
					'modified' => 'Modified',
				),
				'default'    => 'date',
				'dependency' => array( 'wpgpsc_module', 'not-any', 'cd-timer,category' ),
			),
			array(
				'id'         => 'wpgpsc_product_order',
				'type'       => 'button_set',
				'title'      => 'Order',
				'subtitle'   => 'Get largest or last in the order will appear at the top of the list or vice versa.',
				'options'    => array(
					'ASC'  => 'Ascending',
					'DESC' => 'Descending',
				),
				'default'    => 'DESC',
				'dependency' => array( 'wpgpsc_module', 'not-any', 'cd-timer,category' ),
			),
			array(
				'id'         => 'wpgpsc_product_per_page',
				'type'       => 'spinner',
				'title'      => __( 'Item Per Page', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Maximum number of item per page.', 'gpsc-product-slider-carousel' ),
				'default'    => 6,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'slider,grouped,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_review_ids',
				'type'       => 'text',
				'title'      => 'Review IDs',
				'subtitle'   => 'Write some review ids within comma separator. For eg → 5, 6, 8,',
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),

			/**
			 * Visibilities 👇
			 */
			array(
				'type'       => 'subheading',
				'content'    => '<i class="fas fa-grip-lines"></i> Visibilities Only For Highlighted Product <i class="fas fa-grip-lines"></i>',
				'class'      => 'wpgpsc-subheading',
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_img',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Image', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product image for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_name',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Name', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product name for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_excerpt',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Excerpt', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product excerpt for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_rating',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Rating', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product rating for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_price',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Price', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product price for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_stock',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Stock Status', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product stock status for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_sku',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product SKU', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product SKU for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'id'         => 'wpgpsc_highlighted_btn',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Button', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product button for highlighted product.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'type'       => 'subheading',
				'content'    => '<i class="fas fa-grip-lines"></i> Visibilities For All Products <i class="fas fa-grip-lines"></i>',
				'class'      => 'wpgpsc-subheading',
				'dependency' => array( 'wpgpsc_module', '==', 'highlighted' ),
			),
			array(
				'type'       => 'subheading',
				'content'    => '<i class="fas fa-grip-lines"></i> Visibilities <i class="fas fa-grip-lines"></i>',
				'class'      => 'wpgpsc-subheading',
				'dependency' => array( 'wpgpsc_module', 'not-any', 'highlighted,cd-timer' ),
			),

			//
			// Only for table view.
			array(
				'id'         => 'wpgpsc_show_cat_filter',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Category Filter', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide category filter of table view.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_show_search',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Search', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide search for table view.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_show_sorting',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Sorting', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide sorting for table view.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_header_sticky_on',
				'type'       => 'switcher',
				'title'      => __( 'On/Off Header Sticky', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'On/Off header sticky for table view.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'On', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Off', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_column_sticky_on',
				'type'       => 'switcher',
				'title'      => __( 'On/Off Column Sticky', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'On/Off Column sticky for table view.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'On', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Off', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_column_sticky_which',
				'type'       => 'button_set',
				'title'      => 'Column Sticky From',
				'subtitle'   => 'Column sticky form left or right.',
				'options'    => array(
					'left'  => 'First',
					'right' => 'Last',
				),
				'default'    => 'left',
				'dependency' => array( 'wpgpsc_module|wpgpsc_column_sticky_on', '==|==', 'table|true' ),
			),
			array(
				'id'         => 'wpgpsc_show_child_row',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Child Row', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide child row at first column.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_child_row_data',
				'type'       => 'button_set',
				'title'      => 'Select Child Row Data',
				'subtitle'   => 'Select child row data of product table.',
				'options'    => array(
					'desc' => 'Description',
					'attr' => 'Attributes',
				),
				'default'    => 'desc',
				'dependency' => array( 'wpgpsc_module|wpgpsc_show_child_row', '==|==', 'table|true' ),
			),
			array(
				'id'         => 'wpgpsc_show_col_search',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Column Search', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide individual search field in every column.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),
			array(
				'id'         => 'wpgpsc_show_table_footer',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Table Footer', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide table footer.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'table' ),
			),

			// Common.
			array(
				'id'         => 'wpgpsc_pagination_show',
				'type'       => 'switcher',
				'title'      => __( 'Show Pagination', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide the product pagination.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 80,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'slider,grouped,category,reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_thumb',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Thumbnails', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide thumbnails of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'          => 'wpgpsc_thumb_size',
				'type'        => 'select',
				'title'       => 'Set Thumbnail Size',
				'subtitle'    => 'Set thumbnail size of product.',
				'placeholder' => 'Select an option',
				'options'     => array(
					'thumbnail'    => 'Thumbnail',
					'medium'       => 'Medium',
					'medium_large' => 'Medium_large',
					'large'        => 'Large',
					'full'         => 'Full',
				),
				'default'     => 'medium',
				'dependency'  => array( 'wpgpsc_show_thumb|wpgpsc_module', '==|not-any', 'true|reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_reviewer_img',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Reviewer Image', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide image of reviewers.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),
			array(
				'id'         => 'wpgpsc_show_name',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Names', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide names of items.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '!=', 'cd-timer' ),
			),
			array(
				'id'          => 'wpgpsc_name_tag',
				'type'        => 'select',
				'title'       => 'Item Name Tag',
				'subtitle'    => __( 'Select a HTML tag for item name.', 'gpsc-product-slider-carousel' ),
				'placeholder' => 'Select a tag',
				'options'     => array(
					'h1' => 'H1',
					'h2' => 'H2',
					'h3' => 'H3',
					'h4' => 'H4',
					'h5' => 'H5',
					'h6' => 'H6',
				),
				'default'     => 'h3',
				'dependency'  => array( 'wpgpsc_module|wpgpsc_show_name', '!=|==', 'cd-timer|true' ),
			),
			array(
				'id'         => 'wpgpsc_show_price',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Price', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide price of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_short_desc',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Excerpt', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide short description of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_word_count_number',
				'type'       => 'spinner',
				'title'      => __( 'Word Count', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set word count number.', 'gpsc-product-slider-carousel' ),
				'dependency' => array( 'wpgpsc_show_short_desc|wpgpsc_module', '==|not-any', 'true|cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_category',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Category', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide category of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_tag',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Product Tag', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide tag of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_stock_status',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Stock Status', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide stock status of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_button',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Add to Cart', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide add to cart button of products.<br><a href="' . get_admin_url() . 'edit.php?post_type=gpsc_slider_carousel&page=wpgpsc_settings#tab=add-to-cart" target="_blank">Change Add to Cart button text and more..</a>', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_detail_btn',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Details Button', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide details button of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_show_detail_btn_txt',
				'type'       => 'text',
				'title'      => 'Detail Button Text',
				'default'    => 'See Details',
				'dependency' => array( 'wpgpsc_show_detail_btn|wpgpsc_module', '==|not-any', 'true|reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_sale_tag_show',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Sale Tag', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide sale tag of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', 'not-any', 'reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_sale_tag_type',
				'type'       => 'button_set',
				'title'      => 'Sale Tag Types',
				'title'      => 'Sale Tag Types',
				'subtitle'   => 'Set a sale tag type.',
				'options'    => array(
					'tag'         => 'Sale Tag',
					'percent'     => 'Percentage',
					'percent-tag' => 'Sale Tag With Percentage',
				),
				'default'    => 'percent-tag',
				'dependency' => array( 'wpgpsc_sale_tag_show|wpgpsc_module', '==|not-any', 'true|reviews,cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_star_rating_show',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Star Rating', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide star rating of products.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '!=', 'cd-timer' ),
			),
			array(
				'id'         => 'wpgpsc_review_txt_show',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Review Text', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide review text.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),
			array(
				'id'         => 'wpgpsc_review_txt_fixed_height',
				'type'       => 'switcher',
				'title'      => __( 'Review Text Fixed Height', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Over text show with a scroll bar.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_review_txt_show|wpgpsc_module', '==|==', 'true|reviews' ),
			),
			array(
				'id'         => 'wpgpsc_review_date_show',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Date', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide date of reviews.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),
			array(
				'id'         => 'wpgpsc_review_time_show',
				'type'       => 'switcher',
				'title'      => __( 'Show/Hide Time', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide time of reviews.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
				'dependency' => array( 'wpgpsc_module', '==', 'reviews' ),
			),
		),
	)
);

/**
 * Get Product Categories.
 *
 * @return Array Categories.
 */
function wpgpsc_get_product_cat() {

	$cat_arr    = array();
	$orderby    = 'name';
	$order      = 'asc';
	$hide_empty = false;
	$cat_args   = array(
		'orderby'    => $orderby,
		'order'      => $order,
		'hide_empty' => $hide_empty,
	);

	$product_categories = get_terms( 'product_cat', $cat_args );

	if ( ! empty( $product_categories ) ) {

		foreach ( $product_categories as $key => $category ) {

			$cat_arr[ strtolower( $category->name ) ] = $category->name;
		}
	}

	return $cat_arr;
}
