<?php if ( ! defined( 'ABSPATH' ) ) {
	die; } // Cannot access directly.

//
// Create a section.
WPGPSC::createSection(
	$prefix,
	array(
		'title'  => __( 'Gallery', 'gpsc-product-slider-carousel' ),
		'icon'   => 'fa fa-th-large',
		'fields' => array(

			array(
				'type'    => 'notice',
				'style'   => 'warning',
				'content' => '<strong>Note:</strong> These gallery options are for the product gallery on single product pages.<br>
				If you switch off the slider mode, it will turn back to the WooCommerce default view.',
			),
			array(
				'id'         => 'wpgpsc_gallery_slider_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Gallery Slider', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Turn off if you want to keep the default view of product gallery.', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_gallery_section_title_show',
				'type'       => 'switcher',
				'title'      => __( 'Show the section title', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide the section title.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_gallery_section_title_text',
				'type'       => 'text',
				'title'      => __( 'Section Title Text', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set your section title text.', 'gpsc-product-slider-carousel' ),
				'default'    => __( 'Gallery Images :', 'gpsc-product-slider-carousel' ),
				'dependency' => array( 'wpgpsc_gallery_section_title_show', '==', 'true' ),
			),

			// Slider Settings.
			array(
				'id'       => 'wpgpsc_gallery_slider_speed',
				'type'     => 'spinner',
				'title'    => __( 'Slider Speed', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Duration of transition between slides (in ms). Default 300ms.', 'gpsc-product-slider-carousel' ),
				'unit'     => 'ms',
				'default'  => 300,
			),
			array(
				'id'       => 'wpgpsc_gallery_slider_autoplay',
				'type'     => 'switcher',
				'title'    => __( 'Slider Autoplay', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'On/Off slider autoplay.', 'gpsc-product-slider-carousel' ),
				'default'  => false,
			),
			array(
				'id'         => 'wpgpsc_gallery_slider_autoplay_delay',
				'type'       => 'spinner',
				'title'      => __( 'Slider Autoplay Delay', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Delay between transitions (in ms). Default 500ms.', 'gpsc-product-slider-carousel' ),
				'unit'       => 'ms',
				'default'    => 5000,
				'dependency' => array( 'wpgpsc_gallery_slider_autoplay', '==', 'true' ),
			),
			array(
				'id'       => 'wpgpsc_gallery_slider_loop',
				'type'     => 'switcher',
				'title'    => __( 'Slider Loop', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Set to true to enable continuous loop mode.', 'gpsc-product-slider-carousel' ),
				'default'  => false,
			),
			array(
				'id'       => 'wpgpsc_gallery_slides_per_view',
				'type'     => 'spinner',
				'title'    => __( 'Slide Per View', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Number of slides per view (slides visible at the same time on slider\'s container).', 'gpsc-product-slider-carousel' ),
				'default'  => 4,
			),
			array(
				'id'       => 'wpgpsc_gallery_slides_space_between',
				'type'     => 'spinner',
				'title'    => __( 'Slider Space Between', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Distance between slides in px.', 'gpsc-product-slider-carousel' ),
				'default'  => 15,
			),
			array(
				'id'         => 'wpgpsc_gallery_slider_navigation',
				'type'       => 'switcher',
				'title'      => __( 'Show Slider Navigation', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide slider navigation.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_gallery_slider_nav_icon',
				'type'       => 'button_set',
				'title'      => __( 'Navigation Icon', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set a icon for slider navigation.', 'gpsc-product-slider-carousel' ),
				'options'    => array(
					'ico-1' => '<i class="fas fa-angle-right"></i>',
					'ico-2' => '<i class="fas fa-angle-double-right"></i>',
					'ico-3' => '<i class="fas fa-caret-right"></i>',
					'ico-4' => '<i class="fas fa-long-arrow-alt-right"></i>',
					'ico-5' => '<i class="far fa-caret-square-right"></i>',
					'ico-6' => '<i class="far fa-arrow-alt-circle-right"></i>',
					'ico-7' => '<i class="fas fa-caret-square-right"></i>',
					'ico-8' => '<i class="fas fa-chevron-circle-right"></i>',
					'ico-9' => '<i class="far fa-hand-point-right"></i>',
				),
				'default'    => 'ico-1',
				'dependency' => array( 'wpgpsc_gallery_slider_navigation', '==', 'true' ),
			),
			array(
				'id'         => 'wpgpsc_gallery_slider_pagination',
				'type'       => 'switcher',
				'title'      => __( 'Show Slider Pagination', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide slider pagination.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_gallery_slider_pagination_type',
				'type'       => 'button_set',
				'title'      => __( 'Pagination Type', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set a pagination type.', 'gpsc-product-slider-carousel' ),
				'options'    => array(
					'bullets'     => __( 'Bullets', 'gpsc-product-slider-carousel' ),
					'fraction'    => __( 'Fraction', 'gpsc-product-slider-carousel' ),
					'progressbar' => __( 'Progressbar', 'gpsc-product-slider-carousel' ),
				),
				'default'    => 'bullets',
				'dependency' => array( 'wpgpsc_gallery_slider_pagination', '==', 'true' ),
			),
			array(
				'type'    => 'subheading',
				'content' => '<span style="display: block;text-align: center;"><i class="fas fa-grip-lines" style="color: #c1c1c1;margin: 0 10px;"></i> Lightbox Settings <i class="fas fa-grip-lines" style="color: #c1c1c1;margin: 0 10px;"></i></span>',
			),
			array(
				'id'         => 'wpgpsc_gallery_lightbox_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Gallery Lightbox', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Turn off if you want to keep the default view of product gallery.', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => true,
			),
			array(
				'id'                => 'wpgpsc_gallery_lightbox_max_widht',
				'type'              => 'dimensions',
				'title'             => __( 'Maximum Width', 'gpsc-product-slider-carousel' ),
				'subtitle'          => __( 'Maximum width of the lightbox images.', 'gpsc-product-slider-carousel' ),
				'height'            => false,
				'width_icon'        => '',
				'width_placeholder' => '',
				'units'             => array( 'vh' ),
				'default'           => array(
					'width' => '100',
				),
			),
			array(
				'id'         => 'wpgpsc_gallery_lightbox_popup',
				'type'       => 'switcher',
				'title'      => __( 'Popup', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Turn off if you don\'t want to popup the Lightbox.', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => true,
			),
			array(
				'id'       => 'wpgpsc_gallery_lightbox_ratio',
				'type'     => 'button_set',
				'title'    => __( 'Ratio', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Set a ratio for the Lightbox.', 'gpsc-product-slider-carousel' ),
				'options'  => array(
					'16x9' => '16x9',
					'1x1'  => '1x1',
					'4x3'  => '4x3',
					'21x9' => '21x9',
					'full' => 'full',
				),
				'default'  => '16x9',
			),
			array(
				'id'         => 'wpgpsc_gallery_lightbox_share',
				'type'       => 'switcher',
				'title'      => __( 'Share', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'On/Off the share system.', 'gpsc-product-slider-carousel' ),
				'text_width' => 70,
				'default'    => false,
			),
			array(
				'id'          => 'wpgpsc_gallery_lightbox_share_type',
				'type'        => 'select',
				'title'       => 'Share Type',
				'placeholder' => 'Select an option',
				'options'     => array(
					'bar'         => 'Bar',
					'block'       => 'Block',
					'pill'        => 'Pill',
					'transparent' => 'Transparent',
				),
				'default'     => 'bar',
				'dependency'  => array( 'wpgpsc_gallery_lightbox_share', '==', 'true' ),
			),
			array(
				'id'          => 'wpgpsc_gallery_lightbox_spinner_type',
				'type'        => 'select',
				'title'       => 'Spinner Type',
				'subtitle'    => 'Select a spinner type.',
				'placeholder' => 'Select an option',
				'options'     => array(
					'bounce'      => 'Bounce',
					'plane'       => 'Plane',
					'chase'       => 'Chase',
					'wave'        => 'Wave',
					'pulse'       => 'Pulse',
					'flow'        => 'Flow',
					'swing'       => 'Swing',
					'circle'      => 'Circle',
					'circle-fade' => 'Circle Fade',
					'grid'        => 'Grid',
					'fold'        => 'Fold',
					'wander'      => 'Wander',
				),
				'default'     => 'bounce',
			),
			array(
				'id'       => 'wpgpsc_gallery_lightbox_colors',
				'type'     => 'color_group',
				'title'    => __( 'Lightbox Colors', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Set colors for the lightbox.', 'gpsc-product-slider-carousel' ),
				'options'  => array(
					'overlay'  => __( 'Overlay', 'gpsc-product-slider-carousel' ),
					'spinner'  => __( 'Spinner', 'gpsc-product-slider-carousel' ),
					'tools'    => __( 'Tools', 'gpsc-product-slider-carousel' ),
					'tools-bg' => __( 'Tools Background', 'gpsc-product-slider-carousel' ),
				),
				'default'  => array(
					'overlay'  => 'rgba(23, 23, 23, 0.95)',
					'spinner'  => '#d2d2d2',
					'tools'    => '#d2d2d2',
					'tools-bg' => '#1C1C1C',
				),
			),
		),
	)
);
