<?php if ( ! defined( 'ABSPATH' ) ) {
	die; } // Cannot access directly.

//
// Create a section.
WPGPSC::createSection(
	$prefix,
	array(
		'title'  => __( 'Related', 'gpsc-product-slider-carousel' ),
		'icon'   => 'fa fa-random',
		'fields' => array(

			array(
				'type'    => 'notice',
				'style'   => 'warning',
				'content' => '<strong>Note:</strong> Related products are somewhat similar to upsell products, and both are displayed on the single product page. This plugin uses default query from WooCommerce. If you want to showcase your custom-selected products, simply set them up as up-sells.<br>
				Please refer to the detailed <a href="https://woocommerce.com/document/related-products-up-sells-and-cross-sells/" target="_blank">documentation</a> for further instructions.',
			),
			array(
				'id'       => 'wpgpsc_related_slider_show',
				'type'     => 'switcher',
				'title'    => __( 'Related Product Slider', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Turn off if you want to keep the default view of related products.', 'gpsc-product-slider-carousel' ),
				'default'  => true,
			),
			array(
				'type'       => 'submessage',
				'style'      => 'warning',
				'content'    => 'Related products default view is showing now. All of the settings below are not working.',
				'dependency' => array( 'wpgpsc_related_slider_show', '==', 'false' ),
			),
			array(
				'id'       => 'wpgpsc_has_upsell_products',
				'type'     => 'checkbox',
				'title'    => __( 'Show If', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Conditionally show related products if the product has no upsell products.', 'gpsc-product-slider-carousel' ),
				'label'    => 'The product has no upsell products.',
				'default'  => false,
			),
			array(
				'id'       => 'wpgpsc_related_before_upsells',
				'type'     => 'checkbox',
				'title'    => __( 'Show Before Upsell', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Show related products before upsell products.', 'gpsc-product-slider-carousel' ),
				'label'    => 'Yes, I want to show related products first.',
				'default'  => false,
			),

			//
			// Visibilities.
			//
			array(
				'type'    => 'subheading',
				'content' => '<span style="display: block;text-align: center;"><i class="fas fa-grip-lines" style="color: #c1c1c1;margin: 0 10px;"></i> Visibilities Options For Related Products <i class="fas fa-grip-lines" style="color: #c1c1c1;margin: 0 10px;"></i></span>',
			),
			array(
				'id'         => 'wpgpsc_related_section_title_show',
				'type'       => 'switcher',
				'title'      => __( 'Show the section title', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide the section title.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_related_section_title_text',
				'type'       => 'text',
				'title'      => __( 'Section Title Text', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set your section title text.', 'gpsc-product-slider-carousel' ),
				'default'    => __( 'Related Products', 'gpsc-product-slider-carousel' ),
				'dependency' => array( 'wpgpsc_related_section_title_show', '==', 'true' ),
			),
			array(
				'id'         => 'wpgpsc_related_product_img_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Image', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product image.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_related_product_name_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Name', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product name.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_related_product_excerpt_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Excerpt', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product excerpt.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_related_product_cat_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Category', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product category.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_related_product_rating_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Rating', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product rating.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_related_product_stack_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Stack Status', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product stack status.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_related_product_price_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Price', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product price.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_related_product_btn_show',
				'type'       => 'switcher',
				'title'      => __( 'Product Button', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide product button.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),

			//
			// Slider Settings.
			//
			array(
				'type'    => 'subheading',
				'content' => '<span style="display: block;text-align: center;"><i class="fas fa-grip-lines" style="color: #c1c1c1;margin: 0 10px;"></i> Slider Settings For Related Products <i class="fas fa-grip-lines" style="color: #c1c1c1;margin: 0 10px;"></i></span>',
			),
			array(
				'id'       => 'wpgpsc_related_slider_speed',
				'type'     => 'spinner',
				'title'    => __( 'Slider Speed', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Duration of transition between slides (in ms). Default 300ms.', 'gpsc-product-slider-carousel' ),
				'unit'     => 'ms',
				'default'  => 300,
			),
			array(
				'id'       => 'wpgpsc_related_slider_autoplay',
				'type'     => 'switcher',
				'title'    => __( 'Slider Autoplay', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'On/Off slider autoplay.', 'gpsc-product-slider-carousel' ),
				'default'  => false,
			),
			array(
				'id'         => 'wpgpsc_related_slider_autoplay_delay',
				'type'       => 'spinner',
				'title'      => __( 'Slider Autoplay Delay', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Delay between transitions (in ms). Default 500ms.', 'gpsc-product-slider-carousel' ),
				'unit'       => 'ms',
				'default'    => 5000,
				'dependency' => array( 'wpgpsc_related_slider_autoplay', '==', 'true' ),
			),
			array(
				'id'       => 'wpgpsc_related_slider_loop',
				'type'     => 'switcher',
				'title'    => __( 'Slider Loop', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Set to true to enable continuous loop mode.', 'gpsc-product-slider-carousel' ),
				'default'  => false,
			),
			array(
				'id'       => 'wpgpsc_related_slides_per_view',
				'type'     => 'spinner',
				'title'    => __( 'Slide Per View', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Number of slides per view (slides visible at the same time on slider\'s container).', 'gpsc-product-slider-carousel' ),
				'default'  => 4,
			),
			array(
				'id'       => 'wpgpsc_related_slides_space_between',
				'type'     => 'spinner',
				'title'    => __( 'Slider Space Between', 'gpsc-product-slider-carousel' ),
				'subtitle' => __( 'Distance between slides in px.', 'gpsc-product-slider-carousel' ),
				'default'  => 20,
			),
			array(
				'id'         => 'wpgpsc_related_slider_navigation',
				'type'       => 'switcher',
				'title'      => __( 'Show Slider Navigation', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide slider navigation.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgpsc_related_slider_nav_icon',
				'type'       => 'button_set',
				'title'      => __( 'Navigation Icon', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set a icon for navigation of related slider.', 'gpsc-product-slider-carousel' ),
				'options'    => array(
					'ico-1' => '<i class="fas fa-angle-right"></i>',
					'ico-2' => '<i class="fas fa-angle-double-right"></i>',
					'ico-3' => '<i class="fas fa-caret-right"></i>',
					'ico-4' => '<i class="fas fa-long-arrow-alt-right"></i>',
					'ico-5' => '<i class="far fa-caret-square-right"></i>',
					'ico-6' => '<i class="far fa-arrow-alt-circle-right"></i>',
					'ico-7' => '<i class="fas fa-caret-square-right"></i>',
					'ico-8' => '<i class="fas fa-chevron-circle-right"></i>',
					'ico-9' => '<i class="far fa-hand-point-right"></i>',
				),
				'default'    => 'ico-1',
				'dependency' => array( 'wpgpsc_related_slider_navigation', '==', 'true' ),
			),
			array(
				'id'         => 'wpgpsc_related_slider_pagination',
				'type'       => 'switcher',
				'title'      => __( 'Show Slider Pagination', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Show/Hide slider pagination.', 'gpsc-product-slider-carousel' ),
				'text_on'    => __( 'Show', 'gpsc-product-slider-carousel' ),
				'text_off'   => __( 'Hide', 'gpsc-product-slider-carousel' ),
				'text_width' => 75,
				'default'    => false,
			),
			array(
				'id'         => 'wpgpsc_related_slider_pagination_type',
				'type'       => 'button_set',
				'title'      => __( 'Pagination Type', 'gpsc-product-slider-carousel' ),
				'subtitle'   => __( 'Set a pagination type.', 'gpsc-product-slider-carousel' ),
				'options'    => array(
					'bullets'     => __( 'Bullets', 'gpsc-product-slider-carousel' ),
					'fraction'    => __( 'Fraction', 'gpsc-product-slider-carousel' ),
					'progressbar' => __( 'Progressbar', 'gpsc-product-slider-carousel' ),
				),
				'default'    => 'bullets',
				'dependency' => array( 'wpgpsc_related_slider_pagination', '==', 'true' ),
			),
		),
	)
);
